# Site settings
title: Joseph Love
description: BSEE and MSEE at Purdue University
url: "" # Will be https://username.github.io when deployed

# Social links
github_url: https://github.com/shhmow
linkedin_url: https://www.linkedin.com/in/joseph--love/
email: josephlove076@gmail.com

# Build settings
markdown: kramdown
theme: null
plugins: []
